select coalesce(id.central_id, pii.patient_id) as central_id,
       pii.rec_id,
       pii.patient_id,
       pii.faci_id,
       pii. sub_faci_id,
       pii.record_date,
       pii.confirmatory_code,
       pii.uic,
       pii.philhealth_no,
       pii.sex,
       pii.birthdate,
       pii.patient_code,
       pii.philsys_id,
       pii. first,
       pii.middle,
       pii.last,
       pii.suffix,
       test.t0_date,
       test.t0_result,
       test.t1_kit,
       test.t1_date,
       test.t1_result,
       test.t2_kit,
       test.t2_date,
       test.t2_result,
       test.t3_kit,
       test.t3_date,
       test.t3_result,
       confirmatory.confirm_faci,
       confirmatory.confirm_sub_faci,
       confirmatory.confirm_type,
       confirmatory.confirm_code,
       confirmatory.specimen_refer_type,
       confirmatory.specimen_source,
       confirmatory.specimen_sub_source,
       confirmatory.date_collect,
       confirmatory.date_receive,
       confirmatory.confirm_result,
       confirmatory.confirm_remarks,
       confirmatory.signatory_1,
       confirmatory.signatory_2,
       confirmatory.signatory_3,
       confirmatory.date_release,
       confirmatory.date_confirm,
       confirmatory.idnum,
       confirmatory.rt_agreed,
       confirmatory.rt_date,
       confirmatory.rt_result,
       confirmatory.rt_kit,
       confirmatory.rt_vl_requested,
       confirmatory.rt_vl_done,
       confirmatory.rt_vl_date,
       confirmatory.rt_vl_result,
       confirmatory.rita_result,
       pii.created_by,
       pii.created_at,
       pii.updated_by,
       pii.updated_at,
       pii.deleted_by,
       pii.deleted_at
from ohasis_lake.px_hiv_confirmatory as confirmatory
         join ohasis_lake.px_demographics as pii on confirmatory.rec_id = pii.rec_id
         left join ohasis_lake.px_hiv_testing as test on confirmatory.rec_id = test.rec_id
         left join ohasis_lake.id_registry as id on pii.patient_id = id.patient_id
where left(confirmatory.confirm_result, 1) in ('1', '5')
  and coalesce(id.central_id, pii.patient_id) not in
      (select central_id from ohasis_warehouse.harp_dx_old where central_id is not null);
