flow_register()
db$faci_cohort$steps$`01_load_reqs`$.init(envir = db$faci_cohort, yr = "2022", mo = "12")
db$faci_cohort$steps$`02_prepare_harp`$.init(envir = db$faci_cohort)
db$faci_cohort$steps$`03_prepare_reach`$.init(envir = db$faci_cohort)
db$faci_cohort$steps$`04_prepare_prep`$.init(envir = db$faci_cohort)
db$faci_cohort$steps$`05_prepare_cascade`$.init(envir = db$faci_cohort)
db$faci_cohort$steps$`06_upload_db`$.init(envir = db$faci_cohort)
