##  OHASIS Deduplication Controller -------------------------------------------------

source("src/misc/dedup_ohasis/01_pii.R")
source("src/misc/dedup_ohasis/02_dedup_fns.R")

ohasis$data_factory("warehouse", "id_registry", "upsert", TRUE, to = format(Sys.time(), "%Y-%m-%d %H:%M:%S"))
dedup <- dedup_download()
dedup <- dedup_linelist(dedup)

check_dupes <- ohasis_dupes(FIRST, MIDDLE, LAST, UIC)
check_dupes <- ohasis_dupes(FIRST, LAST, UIC)
check_dupes <- ohasis_dupes(FIRST, MIDDLE, LAST, UIC_SORT)
check_dupes <- ohasis_dupes(FIRST, LAST, UIC_SORT)
check_dupes <- ohasis_dupes(FIRST_NY, MIDDLE_NY, LAST_NY, UIC)
check_dupes <- ohasis_dupes(FIRST_NY, LAST_NY, UIC)
check_dupes <- ohasis_dupes(FIRST, MIDDLE, LAST, BIRTHDATE, UIC_ORDER)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_SIEVE, BIRTHDATE, CONFIRM_SIEVE)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_SIEVE, BIRTHDATE, PXCODE_SIEVE)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_SIEVE, BIRTHDATE, PHIC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_SIEVE, BIRTHDATE, PHILSYS)
check_dupes <- ohasis_dupes(FIRST_NY, LAST_NY, BIRTHDATE, CONFIRM_SIEVE)
check_dupes <- ohasis_dupes(FIRST_NY, LAST_NY, BIRTHDATE, PXCODE_SIEVE)
check_dupes <- ohasis_dupes(FIRST_NY, LAST_NY, BIRTHDATE, PHIC)
check_dupes <- ohasis_dupes(FIRST_NY, LAST_NY, BIRTHDATE, PHILSYS)
check_dupes <- ohasis_dupes(FIRST, MIDDLE, LAST_A, UIC)
check_dupes <- ohasis_dupes(FIRST, LAST_A, UIC)
check_dupes <- ohasis_dupes(FIRST_A, MIDDLE, LAST, UIC)
check_dupes <- ohasis_dupes(FIRST_A, LAST, UIC)
check_dupes <- ohasis_dupes(FIRST_A, MIDDLE, LAST_A, UIC)

check_dupes <- ohasis_dupes(FIRST_SIEVE, MIDDLE_SIEVE, LAST_SIEVE, UIC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_SIEVE, UIC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, UIC, CLIENT_MOBILE)
check_dupes <- ohasis_dupes(FIRST_SIEVE, BIRTHDATE, CLIENT_MOBILE)
check_dupes <- ohasis_dupes(FIRST_NY, UIC, CLIENT_MOBILE)
check_dupes <- ohasis_dupes(FIRST_NY, BIRTHDATE, CLIENT_MOBILE)
check_dupes <- ohasis_dupes(FIRST_SIEVE, UIC, CLIENT_EMAIL)
check_dupes <- ohasis_dupes(FIRST_SIEVE, BIRTHDATE, CLIENT_EMAIL)
check_dupes <- ohasis_dupes(FIRST_NY, UIC, CLIENT_EMAIL)
check_dupes <- ohasis_dupes(FIRST_NY, BIRTHDATE, CLIENT_EMAIL)
check_dupes <- ohasis_dupes(FIRST_SIEVE, UIC, PERM_PROV)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_NY, BIRTHDATE, PERM_MUNC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, UIC, CURR_PROV)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_NY, BIRTHDATE, CURR_MUNC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, BIRTHDATE, PXCODE_SIEVE)
check_dupes <- ohasis_dupes(FIRST_SIEVE, BIRTH_YR, CLIENT_MOBILE)
check_dupes <- ohasis_dupes(FIRST_SIEVE, BIRTH_MO, CLIENT_MOBILE)
check_dupes <- ohasis_dupes(FIRST_SIEVE, BIRTH_DY, CLIENT_MOBILE)
check_dupes <- ohasis_dupes(FIRST_NY, BIRTH_YR, CLIENT_MOBILE)
check_dupes <- ohasis_dupes(FIRST_NY, BIRTH_MO, CLIENT_MOBILE)
check_dupes <- ohasis_dupes(FIRST_NY, BIRTH_DY, CLIENT_MOBILE)
check_dupes <- ohasis_dupes(FIRST_SIEVE, BIRTH_YR, CLIENT_EMAIL)
check_dupes <- ohasis_dupes(FIRST_SIEVE, BIRTH_MO, CLIENT_EMAIL)
check_dupes <- ohasis_dupes(FIRST_SIEVE, BIRTH_DY, CLIENT_EMAIL)
check_dupes <- ohasis_dupes(FIRST_NY, BIRTH_YR, CLIENT_EMAIL)
check_dupes <- ohasis_dupes(FIRST_NY, BIRTH_MO, CLIENT_EMAIL)
check_dupes <- ohasis_dupes(FIRST_NY, BIRTH_DY, CLIENT_EMAIL)

check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_A, UIC_1, BIRTH_YR, BIRTH_MO, PERM_MUNC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_A, UIC_1, BIRTH_YR, BIRTH_DY, PERM_MUNC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_A, UIC_1, BIRTH_MO, BIRTH_DY, PERM_MUNC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_A, UIC_2, BIRTH_YR, BIRTH_MO, PERM_MUNC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_A, UIC_2, BIRTH_YR, BIRTH_DY, PERM_MUNC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_A, UIC_2, BIRTH_MO, BIRTH_DY, PERM_MUNC)

check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_A, UIC_1, BIRTH_YR, BIRTH_MO, CURR_MUNC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_A, UIC_1, BIRTH_YR, BIRTH_DY, CURR_MUNC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_A, UIC_1, BIRTH_MO, BIRTH_DY, CURR_MUNC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_A, UIC_2, BIRTH_YR, BIRTH_MO, CURR_MUNC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_A, UIC_2, BIRTH_YR, BIRTH_DY, CURR_MUNC)
check_dupes <- ohasis_dupes(FIRST_SIEVE, LAST_A, UIC_2, BIRTH_MO, BIRTH_DY, CURR_MUNC)

check_dupes <- ohasis_dupes(FIRST_SIEVE, CONFIRM_SIEVE)
check_dupes <- ohasis_dupes(FIRST_NY, CONFIRM_SIEVE)
check_dupes <- ohasis_dupes(FIRST_SIEVE, PXCODE_SIEVE)
check_dupes <- ohasis_dupes(FIRST_NY, PXCODE_SIEVE)
check_dupes <- ohasis_dupes(LAST_SIEVE, CONFIRM_SIEVE, BIRTH_YR)
check_dupes <- ohasis_dupes(LAST_SIEVE, CONFIRM_SIEVE)
check_dupes <- ohasis_dupes(LAST_NY, CONFIRM_SIEVE, BIRTH_YR)
check_dupes <- ohasis_dupes(LAST_NY, CONFIRM_SIEVE)

# upload
upload_dupes(check_dupes$registry_up)
upload_dupes(check_dupes$normal_up)

# new process
from              <- "2023-07-10 11:00:00"
dedup$id_registry <- upload_dupes2(check_dupes$registry_up, dedup$id_registry)
dedup$id_registry <- upload_dupes2(check_dupes$normal_up, dedup$id_registry)

dedup$id_registry <- upload_dupes2(check_dupes$normal_up, dedup$id_registry, TRUE, from)

check_dupes$registry %>% View("reg")
check_dupes$normal %>% View("norm")
