readRenviron(".Renviron")

rm(list = ls())
source("autoload.R")

NcrPridelympics <- R6Class(
   'NcrPridelympics',
   public = list(
      forms       = list(),
      data        = tibble(),
      initialize  = function(min, max) {
         update_hts(min, max)
         self$forms    <- get_hts(min, max)
         self$forms$id <- update_idreg()

         invisible(self)
      },
      consolidate = function() {
         facis <- ohasis$ref_faci %>%
            filter(FACI_NHSSS_REG == "NCR")
         facis <- facis$FACI_ID

         self$data <- process_hts(self$forms$hts, self$forms$a, self$forms$cfbs) %>%
            get_cid(self$forms$id, PATIENT_ID) %>%
            filter(FACI_ID %in% facis, FACI_ID != '130000') %>%
            mutate(
               use_record_faci = if_else(is.na(SERVICE_FACI), 1, 0, 0),
               SERVICE_FACI    = if_else(use_record_faci == 1, FACI_ID, SERVICE_FACI),
            ) %>%
            convert_hts("name") %>%
            generate_gender_identity(SEX, SELF_IDENT, SELF_IDENT_OTHER, gender_identity) %>%
            select(
               REC_ID,
               CENTRAL_ID,
               PATIENT_ID,
               FORM_VERSION,
               CREATED_BY,
               CREATED_AT,
               UPDATED_BY,
               UPDATED_AT,
               REPORT_FACI,
               RECORD_DATE,
               UIC,
               SEX,
               BIRTHDATE,
               AGE,
               AGE_MO,
               SELF_IDENT,
               SELF_IDENT_OTHER,
               NATIONALITY,
               EDUC_LEVEL,
               CIVIL_STATUS,
               IS_STUDENT,
               LIVING_WITH_PARTNER,
               CHILDREN,
               CURR_REG,
               CURR_PROV,
               CURR_MUNC,
               PERM_REG,
               PERM_PROV,
               PERM_MUNC,
               BIRTH_REG,
               BIRTH_PROV,
               BIRTH_MUNC,
               IS_PREGNANT,
               VERBAL_CONSENT,
               SIGNATURE_ESIG,
               SIGNATURE_NAME,
               WORK,
               IS_EMPLOYED,
               IS_OFW,
               OFW_YR_RET,
               OFW_STATION,
               OFW_COUNTRY,
               EXPOSE_HIV_MOTHER,
               EXPOSE_SEX_M,
               EXPOSE_SEX_M_AV_DATE,
               EXPOSE_SEX_M_AV_NOCONDOM_DATE,
               EXPOSE_SEX_F,
               EXPOSE_SEX_F_AV_DATE,
               EXPOSE_SEX_F_AV_NOCONDOM_DATE,
               EXPOSE_SEX_PAYING,
               EXPOSE_SEX_PAYING_DATE,
               EXPOSE_SEX_PAYMENT,
               EXPOSE_SEX_PAYMENT_DATE,
               EXPOSE_SEX_DRUGS,
               EXPOSE_SEX_DRUGS_DATE,
               EXPOSE_DRUG_INJECT,
               EXPOSE_DRUG_INJECT_DATE,
               EXPOSE_BLOOD_TRANSFUSE,
               EXPOSE_BLOOD_TRANSFUSE_DATE,
               EXPOSE_OCCUPATION,
               EXPOSE_OCCUPATION_DATE,
               TEST_REASON_HIV_EXPOSE,
               TEST_REASON_PHYSICIAN,
               TEST_REASON_PEER_ED,
               TEST_REASON_EMPLOY_OFW,
               TEST_REASON_EMPLOY_LOCAL,
               TEST_REASON_TEXT_EMAIL,
               TEST_REASON_INSURANCE,
               TEST_REASON_OTHER_TEXT,
               PREV_TESTED,
               PREV_TEST_DATE,
               PREV_TEST_FACI,
               PREV_TEST_RESULT,
               MED_TB_PX,
               MED_STI,
               MED_HEP_B,
               MED_HEP_C,
               MED_PREP_PX,
               MED_PEP_PX,
               CLINICAL_PIC,
               SYMPTOMS,
               WHO_CLASS,
               REACH_CLINICAL,
               REACH_ONLINE,
               REACH_INDEX_TESTING,
               REACH_SSNT,
               REACH_VENUE,
               TEST_REFUSE_OTHER_TEXT,
               REFER_ART,
               REFER_CONFIRM,
               REFER_RETEST,
               RETEST_MOS,
               RETEST_WKS,
               RETEST_DATE,
               SERVICE_HIV_101,
               SERVICE_IEC_MATS,
               SERVICE_RISK_COUNSEL,
               SERVICE_PREP_REFER,
               SERVICE_SSNT_OFFER,
               SERVICE_SSNT_ACCEPT,
               SERVICE_CONDOMS,
               SERVICE_LUBES,
               CBS_REG,
               CBS_PROV,
               CBS_MUNC,
               CBS_VENUE,
               HTS_REG,
               HTS_PROV,
               HTS_MUNC,
               HTS_FACI,
               HTS_PROVIDER,
               HTS_PROVIDER_TYPE,
               HTS_PROVIDER_TYPE_OTHER,
               EXPOSE_SEX_M_NOCONDOM,
               EXPOSE_SEX_F_NOCONDOM,
               EXPOSE_SEX_HIV,
               EXPOSE_TATTOO,
               EXPOSE_STI,
               AGE_FIRST_SEX,
               AGE_FIRST_INJECT,
               NUM_M_PARTNER,
               YR_LAST_M,
               NUM_F_PARTNER,
               YR_LAST_F,
               MED_IS_PREGNANT,
               MED_CBS_REACTIVE,
               TEST_REASON_RETEST,
               TEST_REASON_NO_REASON,
               EXPOSE_SEX_EVER,
               EXPOSE_M_SEX_ORAL_ANAL,
               EXPOSE_CONDOMLESS_ANAL,
               EXPOSE_CONDOMLESS_ANAL_DATE,
               EXPOSE_CONDOMLESS_VAGINAL,
               EXPOSE_CONDOMLESS_VAGINAL_DATE,
               EXPOSE_NEEDLE_SHARE,
               EXPOSE_NEEDLE_SHARE_DATE,
               EXPOSE_ILLICIT_DRUGS,
               EXPOSE_ILLICIT_DRUGS_DATE,
               EXPOSE_SEX_HIV_DATE,
               TEST_REFUSE_NO_TIME,
               TEST_REFUSE_OTHER,
               TEST_REFUSE_NO_CURE,
               TEST_REFUSE_FEAR_RESULT,
               TEST_REFUSE_FEAR_DISCLOSE,
               TEST_REFUSE_FEAR_MSM,
               gender_identity,
               hts_date,
               hts_result,
               hts_modality,
               test_agreed,
               hts_client_type,
               risk_motherhashiv,
               risk_sexwithf,
               risk_sexwithf_nocdm,
               risk_sexwithm,
               risk_sexwithm_nocdm,
               risk_payingforsex,
               risk_paymentforsex,
               risk_sexwithhiv,
               risk_injectdrug,
               risk_needlestick,
               risk_bloodtransfuse,
               risk_illicitdrug,
               risk_chemsex,
               risk_tattoo,
               risk_sti,
               online_app  = ONLINE_APP,
               sexual_risk = SEXUAL_RISK,
               kap_unknown,
               kap_msm,
               kap_heterom,
               kap_heterof,
               kap_pwid,
               kap_pip,
               kap_pdl,
            ) %>%
            mutate_at(
               .vars = vars(
                  SEX,
                  SELF_IDENT,
                  EDUC_LEVEL,
                  CIVIL_STATUS,
                  LIVING_WITH_PARTNER,
                  IS_PREGNANT,
                  VERBAL_CONSENT,
                  SIGNATURE_ESIG,
                  SIGNATURE_NAME,
                  IS_STUDENT,
                  IS_EMPLOYED,
                  IS_OFW,
                  OFW_STATION,
                  TEST_REASON_HIV_EXPOSE,
                  TEST_REASON_PHYSICIAN,
                  TEST_REASON_PEER_ED,
                  TEST_REASON_EMPLOY_OFW,
                  TEST_REASON_EMPLOY_LOCAL,
                  TEST_REASON_TEXT_EMAIL,
                  TEST_REASON_INSURANCE,
                  PREV_TESTED,
                  PREV_TEST_RESULT,
                  MED_TB_PX,
                  MED_STI,
                  MED_HEP_B,
                  MED_HEP_C,
                  MED_PREP_PX,
                  MED_PEP_PX,
                  CLINICAL_PIC,
                  WHO_CLASS,
                  REACH_CLINICAL,
                  REACH_ONLINE,
                  REACH_INDEX_TESTING,
                  REACH_SSNT,
                  REACH_VENUE,
                  REFER_ART,
                  REFER_CONFIRM,
                  REFER_RETEST,
                  SERVICE_HIV_101,
                  SERVICE_IEC_MATS,
                  SERVICE_RISK_COUNSEL,
                  SERVICE_PREP_REFER,
                  SERVICE_SSNT_OFFER,
                  SERVICE_SSNT_ACCEPT,
                  HTS_PROVIDER_TYPE,
                  MED_IS_PREGNANT,
                  MED_CBS_REACTIVE,
                  TEST_REASON_RETEST,
                  TEST_REASON_NO_REASON,
                  EXPOSE_HIV_MOTHER,
                  EXPOSE_SEX_M,
                  EXPOSE_SEX_F,
                  EXPOSE_SEX_PAYING,
                  EXPOSE_SEX_PAYMENT,
                  EXPOSE_SEX_DRUGS,
                  EXPOSE_DRUG_INJECT,
                  EXPOSE_BLOOD_TRANSFUSE,
                  EXPOSE_OCCUPATION,
                  EXPOSE_SEX_M_NOCONDOM,
                  EXPOSE_SEX_F_NOCONDOM,
                  EXPOSE_SEX_HIV,
                  EXPOSE_TATTOO,
                  EXPOSE_STI
               ),
               ~str_to_title(remove_code(.)) %>%
                  str_replace_all("\\bHiv\\b", "HIV") %>%
                  str_replace_all("\\Cbs\\b", "CBS")
            ) %>%
            mutate_if(
               .predicate = is.Date,
               ~if_else(. < -25567, NA_Date_, ., .)
            ) %>%
            mutate(
               WHO_CLASS        = toupper(WHO_CLASS),
               PREV_TEST_RESULT = case_when(
                  PREV_TEST_RESULT == "Positive" ~ "Reactive",
                  PREV_TEST_RESULT == "Negative" ~ "Non-Reactive",
                  TRUE ~ PREV_TEST_RESULT
               )
            )

         invisible(self)
      },
      export = function () {
         xl <- format(Sys.time(), "%Y%m%d-%I%p-pridelympics.xlsx")
         write_xlsx(self$data, xl)
         drive_upload(xl, as_id("1ISpOaBQjVz0nzJNzXjeqc70dkba-Ndvz"))
         unlink(xl)
      }
   )
)

##  Load primary classes -------------------------------------------------------

# initiate the project & database
ohasis <- DB$new("2025", "05", "pridelympics", "3")

ncr <- NcrPridelympics$new("2025-06-01", format(Sys.time(), "%Y-%m-%d"))
ncr$consolidate()
ncr$export()
