SELECT pii.REC_ID,
       pii.PATIENT_ID,
       pii.FORM_VERSION,
       pii.CREATED_BY,
       pii.CREATED_AT,
       pii.UPDATED_BY,
       pii.UPDATED_AT,
       pii.DELETED_BY,
       pii.DELETED_AT,
       pii.SNAPSHOT,
       pii.FACI_ID,
       pii.SUB_FACI_ID,
       pii.RECORD_DATE,
       service.SERVICE_FACI,
       service.SERVICE_SUB_FACI,
       service.SERVICE_BY,
       service.VISIT_TYPE,
       pii.CONFIRMATORY_CODE,
       pii.UIC,
       pii.PHILHEALTH_NO,
       pii.SEX,
       ob.IS_PREGNANT,
       pii.BIRTHDATE,
       pii.PATIENT_CODE,
       pii.PHILSYS_ID,
       pii.FIRST,
       pii.MIDDLE,
       pii.LAST,
       pii.SUFFIX,
       pii.AGE,
       pii.AGE_MO,
       CASE LEFT(pii.SELF_IDENT, 1)
           WHEN '1' THEN '1_Man'
           WHEN '2' THEN '2_Woman'
           WHEN '3' THEN '3_Other'
           END AS SELF_IDENT,
       pii.SELF_IDENT_OTHER,
       pii.NATIONALITY,
       work.WORK,
       work.WORK_ESTABLISHMENT,
       pii.CURR_PSGC_REG,
       pii.CURR_PSGC_PROV,
       pii.CURR_PSGC_MUNC,
       pii.CURR_ADDR,
       pii.PERM_PSGC_REG,
       pii.PERM_PSGC_PROV,
       pii.PERM_PSGC_MUNC,
       pii.PERM_ADDR,
       pii.CLIENT_MOBILE,
       pii.CLIENT_EMAIL,
       kp.KP_REGISTERED_SW,
       kp.KP_FREELANCE_SW,
       kp.KP_MSM,
       kp.KP_TG,
       kp.KP_PWID,
       kp.KP_PDL,
       kp.KP_OFW,
       kp.KP_PARTNER,
       kp.KP_OFW_PARTNER,
       kp.KP_GENPOP,
       kp.KP_OTHER,
       service.CLIENT_TYPE,
       sti_sx.STI_SX_DISCHARGE_VAGINAL,
       sti_sx.STI_SX_DISCHARGE_ANAL,
       sti_sx.STI_SX_DISCHARGE_URETHRAL,
       sti_sx.STI_SX_DISCHARGE_OROPHARYNGEAL,
       sti_sx.STI_SX_SWOLLEN_SCROTUM,
       sti_sx.STI_SX_PAIN_URINE,
       sti_sx.STI_SX_ULCER_GENITAL,
       sti_sx.STI_SX_ULCER_ORAL,
       sti_sx.STI_SX_WARTS_GENITAL,
       sti_sx.STI_SX_PAIN_ABDOMEN,
       sti_sx.STI_SX_BLISTER,
       sti_sx.STI_SX_ULCERS,
       sti_sx.STI_SX_WARTS,
       sti_sx.STI_SX_MASS,
       sti_sx.STI_SX_FOUL_ODOR,
       sti_sx.STI_SX_RASHES,
       sti_sx.STI_SX_REDNESS,
       sti_sx.STI_SX_LICE,
       sti_sx.STI_SX_ABSCESS,
       sti_sx.STI_SX_OTHER_TEXT,
       remarks.PE_DIAGNOSIS,
       remarks.PE_REMARKS,
       sti_testing.SYPH_RPR_DATE,
       sti_testing.SYPH_RPR_RESULT,
       sti_testing.SYPH_RPR_QUANTI,
       sti_testing.SYPH_TPPATPHA_DATE,
       sti_testing.SYPH_TPPATPHA_RESULT,
       sti_testing.SYPH_TPPATPHA_QUANTI,
       sti_testing.SYPH_OTHER_NAME,
       sti_testing.SYPH_OTHER_DATE,
       sti_testing.SYPH_OTHER_RESULT,
       sti_testing.SYPH_OTHER_QUANTI,
       sti_treat.SYPH_TREATMENT,
       egasp.SPECIMEN_MALE_UREHTRA,
       egasp.SPECIMEN_FEMALE_CERVICAL,
       egasp.SPECIMEN_PHARYNX,
       egasp.SPECIMEN_RECTUM,
       egasp.SPECIMEN_TYPE_OTHER,
       sti_testing.GONO_GRAM_STAIN_DATE,
       sti_testing.GONO_GRAM_PUS,
       sti_testing.GONO_GRAM_NEG_EXTRA,
       sti_testing.GONO_GRAM_NEG_INTRA,
       egasp.IS_SYNDROMIC,
       egasp.SYNDROMIC_ASSESSMENT,
       sti_treat.GONO_TREATMENT,
       sti_testing.BACVAG_GRAM_STAIN_DATE,
       sti_testing.BACVAG_GRAM_STAIN_RESULT,
       sti_testing.BACVAG_GRAM_STAIN_QUANTI,
       sti_testing.BACVAG_OTHER_NAME,
       sti_testing.BACVAG_OTHER_DATE,
       sti_testing.BACVAG_OTHER_RESULT,
       sti_testing.BACVAG_OTHER_QUANTI,
       sti_treat.BACVAG_TREATMENT,
       sti_testing.TRICHO_WET_MOUNT_DATE,
       sti_testing.TRICHO_WET_MOUNT_RESULT,
       sti_testing.TRICHO_WET_MOUNT_QUANTI,
       sti_testing.TRICHO_OTHER_NAME,
       sti_testing.TRICHO_OTHER_DATE,
       sti_testing.TRICHO_OTHER_RESULT,
       sti_testing.TRICHO_OTHER_QUANTI,
       sti_treat.TRICHO_TREATMENT,
       sti_testing.HIV_TEST_DATE,
       sti_testing.HIV_TEST_RESULT,
       sti_testing.HIV_TEST_QUANTI,
       sti_testing.HEPB_TEST_DATE,
       sti_testing.HEPB_TEST_RESULT,
       sti_testing.HEPB_TEST_QUANTI,
       vax.VAX_HEPB_1ST_DONE,
       sti_testing.HEPC_TEST_DATE,
       sti_testing.HEPC_TEST_RESULT,
       sti_testing.HEPC_TEST_QUANTI,
       service.REPORT_NOTES
FROM ohasis_lake.px_pii AS pii
         LEFT JOIN ohasis_lake.px_faci_info AS service ON pii.REC_ID = service.REC_ID
         LEFT JOIN ohasis_lake.px_ob AS ob ON pii.REC_ID = ob.REC_ID
         LEFT JOIN ohasis_lake.px_occupation AS work ON pii.REC_ID = work.REC_ID
         LEFT JOIN ohasis_lake.px_key_pop AS kp ON pii.REC_ID = kp.REC_ID
         LEFT JOIN ohasis_lake.px_sti_sx AS sti_sx ON pii.REC_ID = sti_sx.REC_ID
         LEFT JOIN ohasis_lake.px_remarks AS remarks ON pii.REC_ID = remarks.REC_ID
         LEFT JOIN ohasis_lake.px_sti_testing AS sti_testing ON pii.REC_ID = sti_testing.REC_ID
         LEFT JOIN ohasis_lake.px_sti_treat AS sti_treat ON pii.REC_ID = sti_treat.REC_ID
         LEFT JOIN ohasis_lake.px_egasp AS egasp ON pii.REC_ID = egasp.REC_ID
         LEFT JOIN ohasis_lake.px_vaccine AS vax ON pii.REC_ID = vax.REC_ID
WHERE FORM_VERSION LIKE 'STI%'
  AND ((pii.CREATED_AT BETWEEN ? AND ?) OR
       (pii.UPDATED_AT BETWEEN ? AND ?) OR
       (pii.DELETED_AT BETWEEN ? AND ?));
-- ID_COLS: REC_ID;
-- DELETE: DELETED_AT IS NOT NULL OR FORM_VERSION <> 'STI (v2021)';
