SELECT PATIENT_ID,
       CENTRAL_ID,
       CREATED_AT,
       UPDATED_AT,
       DELETED_AT,
       GREATEST(COALESCE(DELETED_AT, 0), COALESCE(UPDATED_AT, 0), COALESCE(CREATED_AT, 0)) AS SNAPSHOT
FROM ohasis_interim.registry
WHERE ((CREATED_AT BETWEEN ? AND ?) OR
       (UPDATED_AT BETWEEN ? AND ?) OR
       (DELETED_AT BETWEEN ? AND ?));
-- ID_COLS: PATIENT_ID;
