file <- "C:/Users/johnb/Downloads/20240719-dqai-davao_rhwc.xlsx"

drh_hub <- read_excel(file, "hub-202407", col_types = "text") %>%
   rename(
      `PATIENT_CODE`      = 5,
      `LAST`              = 6,
      `FIRST`             = 7,
      `MIDDLE`            = 8,
      `AGE`               = 9,
      `SEX`               = 10,
      `BIRTHDATE`         = 11,
      `DISTRICT`          = 12,
      `PERM_BRGY`         = 13,
      `PERM_MUNC`         = 14,
      `CONFIRM_DATE`      = 15,
      `ARTSTART_DATE`     = 16,
      `RHWC_CODE`         = 17,
      `CONFIRMATORY_CODE` = 18,
      `PHILHEALTH_NO`     = 19,
      `UIC`               = 20,
      `CLIENT_MOBILE`     = 21,
      `ART_CRITERIA`      = 22,
      `LATEST_HGB`        = 23,
      `LATEST_HGB_2024`   = 24,
      `BASELINE_CD4`      = 26,
      `LATEST_CD4`        = 28,
      `LATEST_CD4_2023`   = 29,
      `LATEST_CD4_2024`   = 30,
      `BASELINE_VL`       = 31,
      `LATEST_VL`         = 33,
      `LATEST_VL_2023`    = 34,
      `LATEST_VL_2024`    = 35,
      `BASELINE_XRAY`     = 36,
      `BASELINE_XPERT`    = 37,
      `LATEST_XPERT_2023` = 38,
      `LATEST_XPERT_2024` = 39,
      `BASELINE_DSSM`     = 40,
      `TB_STATUS`         = 41,
      `TB_REGIMEN`        = 42,
      `TB_MEDS`           = 43,
      `TB_TPT`            = 44,

   )