p_load(RODBC)

db      <- "C:/Users/johnb/Documents/2004_be.mdb"
# channel <- odbcConnectAccess2007(db, pwd = "SA2007CCL")
channel <- odbcConnectAccess2007(db)
sqlTables(channel)$TABLE_NAME
data <- sqlFetch(channel, "HIV")

saccl$`2004` <- data

write_rds(saccl, "H:/System/HARP/1_Diagnosis/SACCL/Database/SACCL - HIV Runs/raw_2004-2015.rds")

clean <- lapply(
   saccl,
   rename_all,
   ~case_when(
      . == 'ID' ~ 'year_id',
      . == 'SERO NO' ~ 'serology_num',
      . == 'SERO NUMBER' ~ 'serology_num',
      . == 'SEROLOGY NUMBER' ~ 'serology_num',
      . == 'CRYO BOX NUMBER' ~ 'cryobox_position',
      . == 'CRYOBOX POSITION' ~ 'cryobox_position',
      . == 'FREEZER' ~ 'freezer',
      . == 'DATE RECEIVED' ~ 'date_receive',
      . == 'DATE REQUESTED' ~ 'date_requested',
      . == 'LAB NO' ~ 'labcode',
      . == 'LAB NUMBER' ~ 'labcode',
      . == 'NAME' ~ 'saccl_name',
      . == 'PATIENT NAME/CODE' ~ 'saccl_name',
      . == 'LAB REFERRAL CODE/NAME' ~ 'saccl_name',
      . == 'NEC FORM-A CODE/NAME' ~ 'eb_name',
      . == 'NEC FORM A NAME/CODE' ~ 'eb_name',
      . == 'LAB NOTES/NEC VALIDATION' ~ 'eb_labcode',
      . == 'AGE' ~ 'age',
      . == 'SEX' ~ 'sex',
      . == 'BDAY' ~ 'birthdate',
      . == 'BIRTHDAY' ~ 'birthdate',
      . == 'OCCUPATION' ~ 'occupation',
      . == 'HISTORY OF TRAVEL' ~ 'hx_travel',
      . == 'MODE OF TRANSMISSSION' ~ 'mot',
      . == 'MODE OF TRANSMISSION' ~ 'mot',
      . == 'OR Num' ~ 'or_num',
      . == 'CATEGORY' ~ 'category',
      . == 'SOURCE' ~ 'source',
      . == 'TYPE OF FACILITY' ~ 'source_faci_type',
      . == 'REGION' ~ 'source_region',
      . == 'TEL NOS' ~ 'source_landline',
      . == 'MAILING RECIPIENT' ~ 'source_recipient',
      . == 'MAILING ADDRESS' ~ 'source_address',
      . == 'TEST 1 KIT' ~ 't1_kit',
      . == 'TEST 1 RESULT' ~ 't1_result',
      . == 'TEST 1/result' ~ 't1_result',
      . == 'TEST 1 EIA LOT #' ~ 't1_lot_no',
      . == 'TEST 1 EIA S/CO' ~ 't1_sco',
      . == 'TEST 2 KIT' ~ 't2_kit',
      . == 'TEST 2 RESULT' ~ 't2_result',
      . == 'TEST 2/result' ~ 't2_result',
      . == 'TEST 2 EIA LOT #' ~ 't2_lot_no',
      . == 'TEST 2 EIA S/CO' ~ 't2_sco',
      . == 'TEST 3 KIT' ~ 't3_kit',
      . == 'TEST 3 RESULT' ~ 't3_result',
      . == 'TEST 3/result' ~ 't3_result',
      . == 'TEST 3 EIA LOT #' ~ 't3_lot_no',
      . == 'TEST 3 EIA S/CO' ~ 't3_sco',
      . == 'DATE PERFORMED' ~ 'date_perform',
      . == 'EIA KIT/REAGENT USED' ~ 'eia_kit',
      . == 'EIA KIT NAME' ~ 'eia_kit',
      . == 'S/CO' ~ 'eia_sco',
      . == 'EIA2 KIT NAME' ~ 'eia2_kit',
      . == 'EIA DATE PERFORMED' ~ 'eia_date',
      . == 'EIA2 DATE PERFORMED' ~ 'eia2_date',
      . == 'LOT NO (EIA KIT)' ~ 'eia_lot_no',
      . == 'EIA LOT #' ~ 'eia_lot_no',
      . == 'CUT-OFF VALUE' ~ 'eia_cutoff',
      . == 'CLEIA DATE PERFORMED' ~ 'cleia_date',
      . == 'CLEIA KIT NAME' ~ 'cleia_kit',
      . == 'CLEIA LOT #' ~ 'cleia_lot_no',
      . == 'CLEIA COV' ~ 'cleia_cutoff',
      . == 'CLEIA S/CO' ~ 'cleia_sco',
      . == 'CLEIA RESULT' ~ 'cleia_result',
      . == 'ICT DATE PERFORMED' ~ 'ict_date',
      . == 'ICT KIT NAME' ~ 'ict_kit',
      . == 'ICT LOT #' ~ 'ict_lot_no',
      . == 'ICT COV' ~ 'ict_cutoff',
      . == 'ICT S/CO' ~ 'ict_sco',
      . == 'ICT RESULT' ~ 'ict_result',
      . == 'EIA2 LOT NO' ~ 'eia2_lot_no',
      . == 'EIA2 COV' ~ 'eia2_cutoff',
      . == 'EIA2 ABS' ~ 'eia2_abs',
      . == 'CUT-OFF-VALUE' ~ 'eia_cutoff',
      . == 'ABSORBANCE' ~ 'eia_absorbance',
      . == 'EIA RESULT' ~ 'eia_result',
      . == 'EIA2 RESULT' ~ 'eia2_result',
      . == 'PA KIT USED' ~ 'pa_kit',
      . == 'PA DATE PERFORMED' ~ 'pa_date',
      . == 'LOT NO (PA KIT)' ~ 'pa_lot_no',
      . == 'PA RESULT' ~ 'pa_result',
      . == 'RAPID TEST KIT USED' ~ 'rapid_kit',
      . == 'RAPID DATE PERFORMED' ~ 'rapid_date',
      . == 'LOT NO (RAPID TEST KIT)' ~ 'rapid_lot_no',
      . == 'RAPID TEST RESULT' ~ 'rapid_result',
      . == 'IF reagent/kit used' ~ 'if_kit',
      . == 'LOT NO (IF)' ~ 'if_lot_no',
      . == 'IF Result' ~ 'if_result',
      . == 'WB' ~ 'wb_kit',
      . == 'WB KIT NAME' ~ 'wb_kit',
      . == 'WB DATE PERFORMED' ~ 'wb_date',
      . == 'WBLOT DATE PERFORMED' ~ 'wb_date',
      . == 'LOT NO (WB)' ~ 'wb_lot_no',
      . == 'WB LOT#' ~ 'wb_lot_no',
      . == 'gp 160' ~ 'gp160',
      . == 'gp 110/120' ~ 'gp110_120',
      . == 'p 68' ~ 'p68',
      . == 'p 65' ~ 'p65',
      . == 'p 55' ~ 'p55',
      . == 'p 52' ~ 'p52',
      . == 'gp 41' ~ 'gp41',
      . == 'p 40' ~ 'p40',
      . == 'p 34' ~ 'p34',
      . == 'p 25' ~ 'p25',
      . == 'p 18' ~ 'p18',
      . == 'p 17' ~ 'p17',
      . == 'p 15' ~ 'p15',
      . == 'p 66' ~ 'p66',
      . == 'p 51' ~ 'p51',
      . == 'p 31' ~ 'p31',
      . == 'p 39' ~ 'p39',
      . == 'p 24' ~ 'p24',
      . == 'gp 120' ~ 'gp120',
      . == 'WB Interpretation' ~ 'wb_result',
      . == 'WB INTERPRETATION' ~ 'wb_result',
      . == 'LOT NO (LIATEK)' ~ 'liatek_lot_no',
      . == 'gp 120 LIATEK' ~ 'gp120',
      . == 'gp 41 LIATEK' ~ 'gp41_2',
      . == 'p 31 LIATEK' ~ 'p31',
      . == 'p 24 LIATEK' ~ 'p24',
      . == 'p 17 LIATEK' ~ 'p17_2',
      . == 'gp 105 LIATEK' ~ 'gp105',
      . == 'gp 36 LIATEK' ~ 'gp36',
      . == 'LIATEK Result' ~ 'liatek_result',
      . == 'HIV PCR KIT used' ~ 'pcr_kit',
      . == 'HIV PCR KIT LOT NO' ~ 'pcr_lot_no',
      . == 'HIV PCR RESULT' ~ 'pcr_result',
      . == 'Medical Technologist' ~ 'signatory_medtech',
      . == 'MEDICAL TECHNOLOGIST' ~ 'signatory_medtech',
      . == 'Pathologist' ~ 'signatory_patho',
      . == 'PATHOLOGIST' ~ 'signatory_patho',
      . == 'REMARKS' ~ 'remarks',
      . == 'LAB NOTES' ~ 'lab_notes',
      . == 'Final Result' ~ 'final_result',
      . == 'FINAL RESULT' ~ 'final_result',
      . == 'date rel' ~ 'date_release',
      . == 'DATE RELEASED' ~ 'date_release',
      . == 'Released' ~ 'is_released',
      . == 'RELEASED' ~ 'is_released',
      . == 'REL' ~ 'is_released',
      . == 'KEEP' ~ 'keep',
      . == 'WITH PREVIOUS WB' ~ 'with_prev_wb',
      . == 'HIV-2' ~ 'hiv2',
      . == 'FOR SIGNING' ~ 'for_signature',
      . == 'Previous Lab' ~ 'prev_lab',
      . == 'Previous date confirmation' ~ 'prev_confirm_date',
      . == 'RELEASING OFFICER' ~ 'signatory_releasing',
      . == 'SIGN TO REL' ~ 'sign_to_release',
      . == 'MONTH' ~ 'month',
      . == 'PRIMARY KEY' ~ 'pk',
      . == 'Field1' ~ 'field1',
      TRUE ~ .
   )
)
clean <- lapply(clean, mutate_all, as.character)
clean <- lapply(clean, mutate_all, ~stri_trans_general(str_squish(.), "NFKD"))

conso <- bind_rows(clean, .id = "year") %>%
   arrange(year, labcode) %>%
   relocate(birthdate, occupation, mot, eb_name, eb_labcode, .after = sex) %>%
   relocate(eb_name, .after = saccl_name) %>%
   relocate(final_result, remarks, date_release, .after = date_perform)

write_xlsx(conso, "H:/System/HARP/1_Diagnosis/SACCL/Database/SACCL - HIV Runs/saccl_combined_2004-2015.xlsx")
write_dta(conso, "H:/System/HARP/1_Diagnosis/SACCL/Database/SACCL - HIV Runs/saccl_combined_2004-2015.dta")

